name: "Deploy"
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: trigger-deploy

env:
  NODE_VERSION: "10.x"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN_PERSONAL: ${{ secrets.GH_TOKEN_PERSONAL }}

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        env:
          BASE_PATH: ${{ secrets.BASE_PATH }}
          NODE_VERSION: "10.x"
          BRANCH: "master"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_PERSONAL: ${{ secrets.GH_TOKEN_PERSONAL }}
          URL: "https://gnuno-talks.netlify.app"
        run: |
          npm install
          npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          netlify-config-path: ./netlify.toml
          production-branch: master
          publish-dir: './dist'
          functions-dir: 'functions-dist'
          github-token: ${{ secrets.GH_TOKEN_PERSONAL }}
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
        env:
          NODE_VERSION: "10.x"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_PERSONAL: ${{ secrets.GH_TOKEN_PERSONAL }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 2
