name: "Handle Submission"
on:
  repository_dispatch:
    types: handle-submission

jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - run: 'echo payload ${{ github.event.client_payload.github }} and ${{ github.event.client_payload.speaker }}'
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
