name: "Handle Submission"
on:
  repository_dispatch:
    types: handle-submission

jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - run: 'echo payload ${{ github.event.client_payload }} and ${{ github.event.client_payload.speaker }}'
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
