name: "Handle Submission"
on:
  repository_dispatch:
    types: handle-submission

jobs:
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2.4.0
        env:
          NODE_VERSION: "10.x"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_PERSONAL: ${{ secrets.GH_TOKEN_PERSONAL }}
          BASE_PATH: ${{ secrets.BASE_PATH }}
          speaker:  ${{ github.event.client_payload.speaker }}
          title:  ${{ github.event.client_payload.title }}
          description: ${{ github.event.client_payload.description }}
          bio: ${{ github.event.client_payload.bio }}
          twitter: ${{ github.event.client_payload.twitter }}
          instagram: ${{ github.event.client_payload.instagram }}
          slides: ${{ github.event.client_payload.slides }}
          repo: ${{ github.event.client_payload.repo }}
          ready: ${{ github.event.client_payload.ready }}
          when: ${{ github.event.client_payload.when }}
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        env:
          BASE_PATH: ${{ secrets.BASE_PATH }}
          NODE_VERSION: "10.x"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_PERSONAL: ${{ secrets.GH_TOKEN_PERSONAL }}
        run: |
          npm install
          npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          netlify-config-path: ./netlify.toml
          production-branch: master
          publish-dir: './dist'
          github-token: ${{ secrets.GH_TOKEN_PERSONAL }}
          production-deploy: true
          deploy-message: "Deploy from GitHub Actions"
        env:
          NODE_VERSION: "10.x"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN_PERSONAL: ${{ secrets.GH_TOKEN_PERSONAL }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 2
