name: "On Accepted"
on:
  issues:
    state: closed
    label: Accepted

jobs:
  on-accepted:
    name: Re Creating
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.2
        with:
          token: ${{ secrets.GH_TOKEN_PERSONAL }}
          event-type: trigger-deploy